version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  test-db:
    image: postgres
    restart: always
    ports:
      - "5434:5432" # üëà Note the 5434 port (since we are using 5433 for our regular db)
    environment:
      POSTGRES_PASSWORD: pass123
  mongo-db:
    image: mongo # container image to be used
    restart: always
    ports: # expose ports in ‚Äúhost:container‚Äù format
      - 27017:27017
    environment: #env variables to pass into the container
      MONGODB_DATABASE: nest-course
